# app.yaml
runtime: java11
env: standard
runtime_config:
   jdk: openjdk8
handlers:
-  url: /.*
   script: this field is required, but ignored
resources:
   cpu: 2
   memory_gb: 2.3
   disk_size_gb: 10
   volumes:
   -  name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5
